### ISSUE TITLE
Replace ThemableElement with ThemableMixin

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/fc-applayout#19]
ThemableMixin in Vaadin 23 has support for LitElement

https://github.com/FlowingCode/fc-applayout/blob/7a434b131181699950a7e57a22650e9ae8d2234b/src/fc-applayout.ts#L34

**Comment by mlopezFC** [comment]
Implemented in [this commit](https://github.com/FlowingCode/fc-applayout/commit/c9c2396c11d7216c3f2c8750615ec07a173506fe)
